name: isaidub_database

on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 1
          
    - name: Gradle Permission
      run: chmod 755 ./*
    
    - name: Build
      run: ./check_pg.sh

    - name: Easy-Browser-2.7.0-apk
      uses: actions/upload-artifact@v7
      with:
        name: Easy-Browser-2.7.0-Debug
        path: ./*
    
    
